#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Bharath Kumar Gajjela
# Static CIS compliance check — greps harden.sh for each control.
# Run from repo root: bash tests/cis-check.sh
set -euo pipefail

HARDEN="harden.sh"
PASS=0; FAIL=0; WARN=0

pass() { echo "  PASS  $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL  $1"; FAIL=$((FAIL + 1)); }
warn() { echo "  WARN  $1 (cloud exception)"; WARN=$((WARN + 1)); }

check() {
  local label="$1"; local pattern="$2"
  grep -qE "$pattern" "$HARDEN" && pass "$label" || fail "$label"
}

echo "======================================================"
echo " CIS Ubuntu 22.04 LTS Benchmark — Static Compliance"
echo " Target: $HARDEN"
echo "======================================================"

echo ""
echo "--- Section 1: Initial Setup ---"
check "1.1.1.1  cramfs disabled"        "install cramfs"
check "1.1.1.2  freevxfs disabled"      "install freevxfs"
check "1.1.1.3  jffs2 disabled"         "install jffs2"
check "1.1.1.4  hfs disabled"           "install hfs"
check "1.1.1.5  hfsplus disabled"       "install hfsplus"
check "1.1.1.6  udf disabled"           "install udf"
check "1.1.1.8  usb-storage disabled"   "install usb-storage"
check "1.1.2    /tmp tmpfs nosuid,nodev,noexec" "nosuid,nodev,noexec"
check "1.1.7    /var/tmp tmpfs"         "var-tmp\.mount|var/tmp.*tmpfs"
check "1.1.15   /dev/shm nodev,nosuid,noexec" "dev/shm.*nosuid,nodev,noexec"
check "1.1.22   sticky bit on world-writable dirs" "chmod a\+t"
check "1.3.1    AIDE installed"         "apt-get.*install.*aide"
check "1.3.2    AIDE daily cron"        "aide.*--check.*cron|cron\.d/aide"
check "1.4.1    GRUB audit=1 cmdline"   "audit=1"
check "1.4.2    GRUB cfg permissions"   "chmod og-rwx.*grub\.cfg|grub\.cfg.*chmod"
check "1.5.1    core dumps restricted"  "hard core.*0|suid_dumpable.*=.*0"
check "1.5.2    ASLR enabled"           "randomize_va_space.*=.*2"
check "1.5.4    prelink purged"         "purge prelink"
check "1.6.1    AppArmor installed"     "apt-get.*install.*apparmor"
check "1.6.2    AppArmor enforcing"     "aa-enforce"
check "1.7.1    /etc/issue banner"      "tee /etc/issue"
check "1.7.2    /etc/issue.net banner"  "tee /etc/issue\.net"
check "1.8.1    unattended-upgrades"    "unattended-upgrades"

echo ""
echo "--- Section 2: Services ---"
check "2.1.1    xinetd removed"         "xinetd"
check "2.2.1    time sync (chrony)"     "chrony"
check "2.2.2    X11 server removed"     "xserver-xorg"
check "2.2.3    Avahi removed"          "avahi-daemon"
check "2.2.4    CUPS removed"           "cups"
check "2.2.5    DHCP server removed"    "isc-dhcp-server"
check "2.2.6    LDAP server removed"    "slapd"
check "2.2.7    NFS removed"            "nfs-kernel-server"
check "2.2.8    DNS server removed"     "bind9"
check "2.2.9    FTP server removed"     "vsftpd"
check "2.2.10   HTTP server removed"    "apache2|nginx"
check "2.2.11   IMAP/POP removed"       "dovecot"
check "2.2.12   Samba removed"          "samba"
check "2.2.13   squid removed"          "squid"
check "2.2.14   SNMP removed"           "snmpd"
check "2.2.15   TFTP removed"           "tftpd"
check "2.3.1    NIS client removed"     "\bnis\b"
check "2.3.2    telnet removed"         "\btelnet\b"
check "2.3.3    rsh removed"            "rsh-client"
check "2.3.4    talk removed"           "\btalk\b"
check "2.3.5    ldap-utils removed"     "ldap-utils"

echo ""
echo "--- Section 3: Network ---"
check "3.1.1    IP forwarding disabled"         "ip_forward.*=.*0"
check "3.1.2    packet redirect disabled"       "send_redirects.*=.*0"
check "3.2.1    source route disabled"          "accept_source_route.*=.*0"
check "3.2.2    ICMP redirects disabled"        "accept_redirects.*=.*0"
check "3.2.3    secure redirects disabled"      "secure_redirects.*=.*0"
check "3.2.4    log martians"                   "log_martians.*=.*1"
check "3.2.5    broadcast ICMP ignored"         "icmp_echo_ignore_broadcasts.*=.*1"
check "3.2.6    bogus ICMP ignored"             "icmp_ignore_bogus_error"
check "3.2.7    reverse path filtering"         "rp_filter.*=.*1"
check "3.2.8    TCP SYN cookies"                "tcp_syncookies.*=.*1"
check "3.2.9    IPv6 RA disabled"               "accept_ra.*=.*0"
check "3.3.2    sctp disabled"                  "install sctp"
check "3.3.3    dccp disabled"                  "install dccp"
check "3.3.4    rds disabled"                   "install rds"
check "3.3.5    tipc disabled"                  "install tipc"
warn  "3.3.1    wireless disabled (N/A EC2)"
check "3.4.1    UFW installed"                  "ufw"
check "3.4.2    UFW default deny inbound"       "ufw default deny incoming"
check "3.4.3    UFW SSH allowed"                "ufw.*allow.*OpenSSH|ufw.*limit.*OpenSSH"

echo ""
echo "--- Section 4: Logging & Auditing ---"
check "4.1.1    auditd installed"               "apt-get.*install.*auditd"
check "4.1.2    auditd disk full action"        "disk_full_action.*=.*halt"
check "4.1.3    sudo audit rules"               "\-w.*sudo.*-p x"
check "4.1.5    network env audit"              "sethostname|setdomainname"
check "4.1.6    user mgmt audit"                "useradd.*-p x.*user-mgmt|user-mgmt"
check "4.1.7    login/logout audit"             "faillog.*-p wa|lastlog.*-p wa"
check "4.1.8    session audit"                  "utmp.*-p wa|wtmp.*-p wa"
check "4.1.9    DAC perm mod audit"             "chmod.*auid.*perm-mod|perm-mod"
check "4.1.10   failed file access audit"       "EACCES|EPERM"
check "4.1.11   SUID/SGID audit rules"          "99-privileged\.rules|perm=x.*privileged"
check "4.1.12   filesystem mounts audit"        "\-S mount.*mounts"
check "4.1.13   file deletion audit"            "unlink.*delete|delete"
check "4.1.14   audit config immutable (-e 2)"  "\-e 2"
check "4.2.1    rsyslog installed"              "rsyslog"
check "4.2.3    log file permissions 0640"      "FileCreateMode.*0640"
check "4.3      logrotate compress"             "^compress$|logrotate.*compress"

echo ""
echo "--- Section 5: Access & Authentication ---"
check "5.1.1    cron.allow root-only"           "cron\.allow"
check "5.1.2    cron dirs permissions"          "chmod og-rwx"
check "5.2.1    sshd permissions"               "sshd -t"
check "5.2.2    SSH Protocol 2"                 "PasswordAuthentication no"
check "5.2.4    SSH LogLevel INFO"              "LogLevel.*INFO"
check "5.2.5    SSH X11Forwarding no"           "X11Forwarding no"
check "5.2.6    SSH MaxAuthTries 3"             "MaxAuthTries.*3"
check "5.2.7    SSH IgnoreRhosts yes"           "IgnoreRhosts yes"
check "5.2.8    SSH HostbasedAuth no"           "HostbasedAuthentication no"
check "5.2.9    SSH PermitRootLogin no"         "PermitRootLogin no"
check "5.2.10   SSH PermitEmptyPasswords no"    "PermitEmptyPasswords no"
check "5.2.11   SSH PermitUserEnvironment no"   "PermitUserEnvironment no"
check "5.2.12   SSH approved ciphers"           "chacha20-poly1305|aes256"
check "5.2.13   SSH approved MACs"              "hmac-sha2-512-etm"
check "5.2.14   SSH approved KexAlgorithms"     "curve25519-sha256"
check "5.2.15   SSH LoginGraceTime 30"          "LoginGraceTime.*30"
check "5.2.16   SSH banner"                     "Banner.*issue\.net"
check "5.2.17   SSH AllowGroups"                "AllowGroups sshusers"
check "5.2.18   SSH MaxStartups"                "MaxStartups.*10:30:60"
check "5.2.19   SSH MaxSessions 4"              "MaxSessions.*4"
check "5.3.1    PAM pwquality"                  "pam_pwquality"
check "5.3.2    PAM lockout (faillock)"         "pam_faillock|faillock"
check "5.3.3    PAM password reuse (remember)"  "remember.*=.*5"
check "5.3.4    SHA-512 password hashing"       "ENCRYPT_METHOD SHA512|sha512"
check "5.4.1    password expiry 365 days"       "PASS_MAX_DAYS.*365"
check "5.4.2    password min days 1"            "PASS_MIN_DAYS.*1"
check "5.4.3    password warn 7 days"           "PASS_WARN_AGE.*7"
check "5.4.4    inactive lock 30 days"          "INACTIVE.*30|useradd.*-f.*30"
check "5.4.5    shell timeout TMOUT<=900"        "TMOUT=[1-9][0-9]{1,2}$"
check "5.4.6    system accounts nologin"        "nologin.*sysuser|usermod.*nologin"
check "5.5      su restricted to wheel/sudo"    "pam_wheel"

echo ""
echo "--- Section 6: System Maintenance ---"
check "6.1.2    /etc/passwd permissions 644"    "chmod 0644.*passwd"
check "6.1.3    /etc/shadow permissions 640"    "chmod 0640.*shadow"
check "6.1.4    /etc/group permissions 644"     "chmod 0644.*group"
check "6.1.5    /etc/gshadow permissions 640"   "chmod 0640.*gshadow"
check "6.2.1    no empty-password accounts"     "passwd -l.*emptyuser|empty.*passwd"

echo ""
echo "======================================================"
printf " Results: %s PASS  |  %s FAIL  |  %s WARN (cloud exceptions)\n" "$PASS" "$FAIL" "$WARN"
echo "======================================================"

[ "$FAIL" -eq 0 ] && exit 0 || exit 1
